language: node_js
node_js:
  - 16

services:
  - docker

git:
  submodules: true
  
stages:
  - name: deploy
    if: branch = niceday/main
    script: docker build -t sensehealth/cal:master . && docker push sensehealth/cal:master
