language: node_js
node_js:
  - 16

services:
  - docker

before_install:
- git submodule update --init

script:
- cd calendso && yarn install && cd ..
- if [ "$TRAVIS_BRANCH" == "niceday/main" -a "$TRAVIS_EVENT_TYPE" == "push" ]; then
    docker build -t sensehealth/cal:master .;
    docker tag sensehealth/cal:master sensehealth/cal:latest;
  elif [ "$TRAVIS_BRANCH" == "niceday/develop" -a "$TRAVIS_EVENT_TYPE" == "push" ]; then
    docker build -t sensehealth/cal:develop .;
  fi

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push --all-tags sensehealth/cal;